@startwbs カレーを作る
* カレーを作る

**[#Aqua] 調理の準備をする
***[#Yellow] 調理器具を用意する
***[#Yellow] 材料を用意する
***[#Yellow] 手を洗う
***[#Yellow] 米を炊く

**[#Aqua] 調理する
***[#Yellow] 野菜を洗う
***[#Yellow] 皮をむく
***[#Yellow] 野菜を切る
***[#Yellow] 肉を切る
***[#Yellow] 肉を炒める
***[#Yellow] 野菜を炒める
***[#Yellow] 水を入れる
***[#Yellow] 混ぜながら煮込む
***[#Yellow] 塩、胡椒を入れる
***[#Yellow] あくを取りながら煮込む
***[#Yellow] コンソメとカレールウを入れる
***[#Yellow] 牛乳を入れてさらに煮込む

**[#Aqua] 食べる準備をする
***[#Yellow] カレー皿に米とカレーを盛り付ける
***[#Yellow] 配膳する
@endwbs
