@startwbs 夕食を作る
* 夕食を作る

**[#Aqua] 食材を買う
***[#Yellow] 全員からお金を受け取る
***[#Yellow] スーパーで食材を買う

**[#Aqua] 調理する
***[#Yellow] ご飯を炊く
***[#Yellow] カレーを作る
***[#Yellow] スープを作る

**[#Aqua] 食べる準備をする
***[#Yellow] 食器を用意する
***[#Yellow] 全ての料理を盛り付ける
***[#Yellow] 配膳する
@endwbs