@startuml カレーを作る
start
fork
  :調理器具を用意する;
  :材料を用意する;
  :手を洗う;
  :米を炊く;
fork again
  :野菜を洗う;
  :皮をむく;
  :野菜を切る;
  :肉を切る;
  :肉を炒める;
  :野菜を炒める;
  :水を入れる;
  :混ぜながら煮込む;
  :塩、胡椒を入れる;
  :あくを取りながら煮込む;
  :コンソメとカレールウを入れる;
  :牛乳を入れてさらに煮込む;
end fork
:カレー皿に米とカレーを盛り付ける;
:配膳する;
stop
@enduml
